### ISSUE TITLE
Cannot figure out how to do Assignment 4, Question 1/Part 2. 

### ISSUE THREAD

**Issue by taylorburtch** [edquant/edh7916#15]
Question 1 asks us to "compute the difference between each student's test score and that of the region." I have been playing around with some online sources, and it appears it might be some sort of mutate command?? At first I thought it would be "diff()", but it does not look like that aligns with where we are in the class. Has anyone else figured out how to do this?

**Comment by btskinner** [comment]
@taylorburtch, you are on track with considering `mutate()`. Check out @jharsell's issue (#16), which may have the other part of the answer you're looking for.

**Comment by btskinner** [comment]
Closing, but reopen if you have questions later.
