### ISSUE TITLE
Assignment 4 - part 2 of question 1

### ISSUE THREAD

**Issue by jharsell** [edquant/edh7916#16]
Hi All,

After spending an embarrassing amount of time on part 2 of question one, I am stuck. Here is the is my latest code after rereading the lesson and StackOverflow on join commands and subtraction:

```R
df_tmp3 <- df_joined %>%
  filter(x1txmtscor > 0, stu_id) %>%
  left_join(by = "stu_id",x1txmtscor - test_scr_mean) 
```

Anyone have any advice on what I am omitting or where I am going wrong?

**Comment by btskinner** [comment]
@jharsell, take another look at your last line:
```r
left_join(by = "stu_id",x1txmtscor - test_scr_mean)
```
You are trying to both _join_ and _add_ (or _mutate_) a new column in the same `left_join()` function. Try splitting those into two separate steps.

**Comment by btskinner** [comment]
Linking @taylorburtch's issue (#15), which is on track for the other part of the answer to this question.

**Comment by btskinner** [comment]
Closing, but reopen if you have new questions later.
