### ISSUE TITLE
data dictionaries and codebooks

### ISSUE THREAD

**Issue by klvogelanderson** [edquant/edh7916#20]
Hi everyone.
Where do you find the data dictionary, or code book, for each IPEDS file? The data dictionary is mentioned in our assignment ("**Click the “continue” button on this page** to see the data and accompanying dictionary files"). However, when I click the link to get to that page, I don't see "continue." Am I missing something really obvious? I also tried searching IPEDS using each file name (hd2007, ic2007mission), but there are no results. Did you all have any luck? I suppose I can do the assignment without the code book, but I wanted to filter out any missing data.
Thanks so much.
Katie

**Comment by btskinner** [comment]
@klvogelanderson: you may be at the wrong link (IPEDS gives a few ways to download the data and it's not easy to get from one to another). Try this link: [https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx](https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx) 

You may have to click continue twice on two pages (the second time after selecting **2007** for the data year from the drop down), but you should end up with a page that looks like this. The dictionary files are highlighted.

![Screen Shot 2020-02-17 at 7 50 32 AM](https://user-images.githubusercontent.com/4744029/74655524-7c261b00-515a-11ea-86aa-5f1d6a9acd53.png)

**Comment by klvogelanderson** [comment]
Thank you so much! I appreciate it. :)

**Comment by btskinner** [comment]
No problem! 

Closing now, but feel free to reopen if you have a question.
