### ISSUE TITLE
Review questions prior to spring break

### ISSUE THREAD

**Issue by btskinner** [edquant/edh7916#21]
@edquant/team_class,

I want to use part of our class this week (2/25) to answer questions you may have over material we've covered. Anything we've discussed is fair game:

- git / GitHub
- Markdown
- dplyr verbs (_e.g._, `mutate()`, `filter()`, `select()`, _etc_)
- pipes (`%>%`)
- joins
- regular expressions (don't want to get _too_ into the weeds here, but happy to answer some questions)
- dates
- control flow functions: `if`, `for`, _etc_
- user-written functions
- (other things I've forgotten off the top of my head)

To make sure I can come prepared with good answers, please ask your question in this thread with as much detail as you can give. If you see a question you also want answered, give it a thumbs up.

**Comment by klvogelanderson** [comment]
Hello Ben! Gosh, I am really struggling this week with assignment 6. Do you think we can go over it tomorrow as a group? The for loops are giving me trouble and the function is blowing my mind. :) 
Of your list above - I would like to please go over for loops and functions. 
Thanks so much.
Katie
