### ISSUE TITLE
IPEDS Data Users - Error: cannot allocate vector of size

### ISSUE THREAD

**Issue by jharsell** [edquant/edh7916#25]
Good morning All,

I hope everyone is enjoying spring break! I am attempting to construct a data frame using 8 separate files, four of which have over 330,000 observations of 64 variables (I only need a handful of said variables). I suspect because of the size of these files R does not want to play nice; what I have gleaned from [StackOverflow](https://community.rstudio.com/t/error-cannot-allocate-vector-of-size-196-1-mb-in-addition-warning-message/9016/3). 

Here is the issue in 
```R
Error: cannot allocate vector of size 335.1 Mb
> df_c_joined <- df %>%
+   left_join(df_1, by = "UNITID")
Error: cannot allocate vector of size 335.0 Mb
```
My questions:
1. Can I drop the variables I do not need in each of my 8 data frames before I start joining them to mitigate this issue?
2. If not, how do I work around the ***Error: cannot allocate vector of size*** to get to my analysis?

**Comment by btskinner** [comment]
Just saw this, @jharsell. Apologies. Two things.

1. The plain meaning of the message is that R / your computer is running out of memory (RAM), so it can't complete the operation. You suspicion is correct. 
2. That said, while 335 Mb isn't _nothing_, it also isn't massive (as in multiple GBs). Either 
    1. you have a lot going on in the background on your machine and R doesn't have enough memory to work with, or 
    2. you have accidentally tried to join two long data frames in which `UNITID` is repeated in each, meaning you end up with exponentially increasing rows

I have had both of these issues at one time or another...

To answer your specific questions:
1. Yes, and I would recommend it.
2. I would need to see more code prior to this join, but my first response will be (if the first step doesn't work): 
    1. restart your R session (clearing your memory)
    2. restart your computer and make sure any memory hogging applications aren't open
