### ISSUE TITLE
Install TinyTex and get luatex.dll error message

### ISSUE THREAD

**Issue by nszekeres** [edquant/edh7916#26]
Hi, got this message when installing TinyTex... is this a problem?

I read that others ignored this message: "There might be an error dialog or two about luatex.dll during the installation (like this), but that does not seem to hurt, and I just clicked “OK”."

PS. Install on Windows machine

ty, 
Naomi

**Comment by btskinner** [comment]
Hi @nszekeres, it looks like there might be a problem with [TeXLive](https://github.com/yihui/tinytex/issues/210#issuecomment-628375903). Hopefully it will be resolved in a couple of days. Give it another go in a day or so.

The good news is that you don't necessarily need LaTeX at the moment (you can just preview your Markdown files as HTML).

ps. Thanks for posting here!

**Comment by AngelClaudio** [comment]
In the past day I've also been getting an issue when trying to knit to PDF. If I run tinytex::tlmgr_update() I will get this following error:
![2020-05-15_0054](https://user-images.githubusercontent.com/17675981/82016054-2cb69480-964e-11ea-8128-73c600b48b8b.png)

**Comment by Vidhipa** [comment]
even i am getting this issue is there any way to solve this issue. I have a lot of pending assignments please help

**Comment by btskinner** [comment]
@AngelClaudio: I think so.

@Vidhipa: This repo is for a course and not directly related to this issue with tinytex / texlive, so I don't have any better solutions than to wait until texlive is updated and tinytex works again. If you can't wait, people on other threads have suggested just installing MikTeX instead.

**Comment by AngelClaudio** [comment]
> @AngelClaudio: I think so.
> 
> @Vidhipa: This repo is for a course and not directly related to this issue with tinytex / texlive, so I don't have any better solutions than to wait until texlive is updated and tinytex works again. If you can't wait, people on other threads have suggested just installing MikTeX instead.

@btskinner I'm a bit confused, I did install MikTeX, should I have something else installed?

**Comment by btskinner** [comment]
@AngelClaudio, then I guess my suggestion isn't correct. I don't know. My understanding is that there's been a (very rare) bug introduced in the upstream TeX chain and that it's filtering down into this issue. It might just be a few days until the bug is fixed and everything goes back to working as normal.

**Comment by kokbent** [comment]
Have same issue and eagerly waiting the problem to be resolved.

Temporary solution: You still get the .tex file (from knitting Rmd), so you can copy that .tex file and use other services like Overleaf to render it to pdf.

**Comment by AngelClaudio** [comment]
> even i am getting this issue is there any way to solve this issue. I have a lot of pending assignments please help

@Vidhipa just FYI you can knit to HTML, open in browser, and print, save as PDF as a work around for now.

**Comment by kokbent** [comment]
https://github.com/yihui/tinytex/issues/210#issuecomment-629429529

I've done this and it works now.

**Comment by btskinner** [comment]
Thanks, @kokbent!

So it seems that these steps may help
```r
tinytex::uninstall_tinytex()
tinytex::install_tinytex()
```
You may get some warnings from the first step, but it's probably just fine. Go ahead and move forward with the second step to install.

See the thread that @kokbent links for more information.

**Comment by nszekeres** [comment]
@btskinner - thanks for the insight on the issue I posted... I'll remove/rerun as you suggested. Right now, it actually gave me an issue when I tried to complete Assignment 1 - part 2. The text rendered in html, but wouldn't render in PDF - it cited the luatex issue. Best, Naomi

**Comment by Chechoblues** [comment]
> tinytex::tlmgr_update()

¡THANK YOU! <3

**Comment by btskinner** [comment]
@nszekeres - it's rare, but sometimes these things happen with R libraries. HTML is fine right now. If it's not fully resolved itself by now, it will soon.
