### ISSUE TITLE
Q1 of Assignment 9 (Pulling in the Source File locations)

### ISSUE THREAD

**Issue by nszekeres** [edquant/edh7916#37]
Hello, @btskinner - I understood what you mean conceptually now (specifically, the sometimes priority to record where data is coming from), but I'm still not able to actually DO what is needed:

I think I got the first part:

```
## get names (with full path) of all school test score files
files <- list.files(bys_dir, full.names = TRUE)
## show
files
```
Then, I pull the files:
```
## init list
df_list <- list()
## use loop to read in files
for (i in 1:length(files)) {
  ## read in file (f) and store in list (note double brackets for list)
  df_list[[i]] <- read_csv(files[i])    
}
## filter files to be read in using pattern
files_bn <- list.files(bys_dir, pattern = "bend|niagara", full.names = TRUE)
## check
files_bn

```

But, I am definitely stuck here - my two questions are:
1) What function should I use to mutate? Is what I'm attempting even legal??
2) I understand that theoretically I stored the location as an object, but I'm not sure what object that is... is that the "i" ??

```
df_list_2 <- df_list %>%
  mutate(relative_path = contains("bend", i, relative_path),
         relative_path = contains("niagra", i, relative_path))
df_list_2
```
Or, I could think about the question/solution this way:

```
for (i in SOME UNKNOWN FUNCTION?) {
  mutate(relative_path = contains("bend", i, relative_path),
         relative_path = contains("niagra",i, relative_path))
}

```
Then, I think I understand the last part... binding has not actually worked yet, but I can probably get it with some fiddling once I solve the first portion.

```
## bind our list to single data frame ###CONFIRM THIS - NOT WORKING###
df_bind <- files_bn %>%
  bind_rows()
## show
df_bind
```

**Comment by btskinner** [comment]
Closing since it's older
