### ISSUE TITLE
stuck in a mode that won't run commands

### ISSUE THREAD

**Issue by LeeDelaino** [edquant/edh7916#4]
I cannot get out of the mode where the commands won't run--this is what I see in my console (I actually don't know what to google)
![image](https://user-images.githubusercontent.com/59539480/72748572-9c77af80-3b85-11ea-8e13-1e6f7133aca8.png)

**Comment by btskinner** [comment]
The `+` means that the R console is waiting for more input. The usual culprit is that you've opened a `(` or `"` without closing it and are now stuck b/c R thinks you are still entering the initial command. Does [this solution](https://stackoverflow.com/a/18803911) help?

**Comment by btskinner** [comment]
@LeeDelaino, did you get this sorted out?

**Comment by btskinner** [comment]
@LeeDelaino, closing since I haven't heard anything. Feel free to reopen if you are still having this issue.
