### ISSUE TITLE
Trouble in using git in Windows desktop 

### ISSUE THREAD

**Issue by BaldwinW** [edquant/edh7916#57]
After I downloaded and installed Git, I don't know why I could not use any git command in R studio console. But I can create a new git project to connect with my git profile although I cannot commit any action.  R studio is the latest version. Is there any other step I missed? 
Thank you.

> which git
Error: unexpected symbol in "which git"

**Comment by btskinner** [comment]
@BaldwinW, are you on a Mac or PC? Also have you had it work before? If so, did you recently update? You may need to restart your computer. Try that first and then let me know if you still can't get it.
