### ISSUE TITLE
R cheatsheets

### ISSUE THREAD

**Issue by btskinner** [edquant/edh7916#6]
There are a number of "cheat sheets" available for RStudio and R code, particularly the Tidyverse. They are **very** helpful and contain a lot of information in a small space. Here are a few you may find useful right now.

- [RStudio](https://rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf)
- [Base R](https://rstudio.com/wp-content/uploads/2016/10/r-cheat-sheet-3.pdf)
- [Reading files with **readr**](https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf)
- [Manipulation with **dplyr**](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)

You can find more [at the RStudio website here](https://rstudio.com/resources/cheatsheets/).

**Comment by btskinner** [comment]
Adding @edquant/team_class to make sure that everyone sees these.

**Comment by LeeDelaino** [comment]
This will be really helpful! Thanks!

**Comment by btskinner** [comment]
Adding some more R cheat sheets in preparation for today's class:

- [Manipulating strings with **stringr**](https://github.com/rstudio/cheatsheets/raw/master/strings.pdf)
- [Working with dates and times using **lubridate**](https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf)

**Comment by btskinner** [comment]
There is also an RMarkdown cheat sheet on this page: [https://rstudio.com/resources/cheatsheets/](https://rstudio.com/resources/cheatsheets/)

- [Direct download](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)
